---

### nginx
- name: install nginx
  apt: name={{ item }} update_cache=yes state=latest force=yes
  with_items:
    - nginx
  become: yes

- name: uncomment server_names_hash_bucket_size  in nginx.conf
  replace:
    destfile: /etc/nginx/nginx.conf
    regexp: '^\s*#(\s*server_names_hash_bucket_size.*)$'
    replace: '\1'    
  become: yes

- name: delete sites-enabled/default
  file: 
      path: /etc/nginx/sites-enabled/default
      state: absent
  notify:
    - restart nginx
  become: yes

- name: chmod/chown {{ web_dir }}
  file: 
    path: "{{ web_dir }}"
    owner: "{{ deploy_user_name }}"
    group: www-data
    mode: 0775
    state: directory
  become: yes