---
- hosts: test
  become: yes
  become_method: sudo


  tasks:
  - name: disable root ssh 
    lineinfile: dest=/etc/ssh/sshd_config regexp='^(.*)PermitRootLogin' line='PermitRootLogin no'
    notify:
      - restart ssh

  # - name: configure and enable firewall
  #   command: "{{ item }}"
  #   with_items:
  #   - ufw allow ssh
  #   - ufw allow 80/tcp   # http
  #   - ufw allow 443/tcp  # https
  #   - ufw allow 25/tcp 	# smtp
  #   - ufw enable		# enable

  - name: Enable UFW
    ufw: direction=incoming policy=deny state=enabled

  - name: UFW limit SSH
    ufw: rule=limit port=ssh

  - name: UFW open HTTP
    ufw: rule=allow port=http

  - name: UFW open HTTPS
    ufw: rule=allow port=https

  - name: install ntp
    apt: name=ntp update_cache=yes  

  - name: make swap
    command: "{{ item }}"
    with_items:
    - fallocate -l 1G /swapfile
    - chmod 600 /swapfile
    - mkswap /swapfile
    - swapon /swapfile
    - sh -c 'echo "/swapfile none swap sw 0 0" >> /etc/fstab'


  handlers:
  - name: restart ssh
    service: name=ssh state=restarted