---
- hosts: snd
  gather_facts: no
  pre_tasks:
    - raw: sudo apt-get -y install python-simplejson
  become: yes
  become_method: sudo

  roles:
    - common
    - mysql
    - php
    - node
    - home
    - wimf    
    - letsencrypt
    - headless-browser