---
## test sudo logrotate -f /etc/logrotate.d/mysql-bkup
## restore: mysql -uroot -psecret < db.sql

- name: copy mysql-bkup file with root password credentials
  template: src=mysql-bkup.j2 dest=/etc/logrotate.d/mysql-bkup owner=root mode=0600  

- name: Creates directories
  file: path={{ backup_dir }}/{{ item }} state=directory owner=athill group=root mode=0775 recurse=yes
  with_items: "{{ backup_stages }}"

- name: create starting files
  file: path={{backup_dir}}/{{item}}/db.sql.gz state=touch owner=athill group=root mode=0644
  with_items: "{{ backup_stages }}"
