---

### not sure these are necessary
# - file:
#     path: "/home/{{ deploy_user_name }}/.config/composer"
#     state: directory
#     mode: 0755

# - name: add auth.json file
#   template: src=github-oauth.json.j2 dest="/home/{{ deploy_user_name }}/.config/composer/auth.json" owner="{{ deploy_user_name }}"


# composer
- name: "{{ host }} composer install"
  composer: 
    command: install 
    working_dir: "{{ project_dir }}" 
#  when: cloned|changed

## node
- name: "{{ host }} set NODE_ENV"
  shell: export NODE_ENV={{ app_env }}

- name: "{{ host }} remove node_modules"
  file:
    state: absent
    path: "{{ project_dir }}/node_modules"

- name: "{{ host }} npm install"
  shell: npm install
  args:
    chdir: "{{ project_dir }}"

- name: "{{ host }} npm build"
  command: "{{ item }}"
  with_items:
    - "{{ node_build_command }}"
  args:
    chdir: "{{ project_dir }}"

### .env
- name: "{{ host }} copy .env file"
  template: src={{ app_name }}.env.j2  dest={{ project_dir }}/.env force=yes


# artisan migrate
- name: "{{ host }}  artisan migrate"
  shell: php "{{ project_dir }}/artisan" migrate --force
  args:
    chdir: "{{ project_dir }}" 
  when: db_database is defined and db_database

- name: Install artisan scheduler cron for {{ host }} 
  cron: 
    name: "Run scheduler for {{ app_name }}"  
    job: "php {{ project_dir }}/artisan schedule:run >> /dev/null 2>&1"

