---

# database 
- name: create application db
  mysql_db: name="{{ db_database }}" state=present

- name: create application database user
  mysql_user: name="{{ db_user }}" password="{{ db_password }}" priv={{ db_database }}.*:ALL state=present