---


- name: stop nginx
  become: yes
  service: name=nginx state=stopped

- name: install cert
  become: yes
  shell: certbot --nginx -d {{ host }} -d www.{{ host }}

# - name: Configure {{ host }} nginx
#   become: yes
#   template: src=nginx-ssl.conf.j2 dest=/etc/nginx/sites-available/{{ host }}  

# - name: create {{ host }} .well-known directory
#   become: yes
#   file: path={{ project_dir }}/public/.well-known state=directory mode=0755 owner={{ deploy_user_name }} group=www-data

# - name: run letsencrypt
#   become: yes
#   shell: letsencrypt certonly --standalone --agree-tos --config /usr/local/etc/le-renew-{{ host }}.ini
#   args: 
#     chdir: /opt/letsencrypt
#     creates: /etc/letsencrypt/live/{{host}}/fullchain.pem

- name: start nginx
  become: yes
  service: name=nginx state=started

# - name: copy {{ host }} renewal script
#   become: yes
#   template: src=le-renew.j2 dest=/usr/local/sbin/le-renew-{{ host }} mode=0700


                