---

- name: Set mysql root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{ db_root_password | quote }}' vtype='password'
  become: yes

- name: Confirm mysql root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ db_root_password |quote }}' vtype='password'
  become: yes

- name: install pip3
  apt: name=python3-pip state=present 

- name: Make sure pymysql is present
  become: yes
  pip:
    name: pymysql
    state: present

- name: install mysql
  apt: name={{ item }} update_cache=yes state=latest force=yes
  with_items: 
    - mysql-server
    - libmysqlclient-dev
    - mysql-client
  become: yes

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  become: yes

- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true
  become: yes
 

