---

- name: Set MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{ db_root_password | quote}}' vtype='password'

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ db_root_password | quote}}' vtype='password'

- name: install mysql
  apt: name={{ item }} update_cache=yes state=latest force=yes
  with_items: 
    - python-mysqldb  
    - mysql-server
    - libmysqlclient-dev
    - mysql-client

- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600  


- name: create application db
  mysql_db: name="{{ db_database }}" state=present

- name: create application user
  mysql_user: name="{{ db_user }}" password="{{ db_password }}" priv={{db_database}}.*:ALL state=present