---

- name: Set mysql root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{ db_root_password | quote }}' vtype='password'
  become: yes

- name: Confirm mysql root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ db_root_password |quote }}' vtype='password'
  become: yes

- name: install mysql
  apt: name={{ item }} update_cache=yes state=latest force=yes
  with_items: 
    - python-mysqldb  
    - mysql-server
    - libmysqlclient-dev
    - mysql-client
  become: yes

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  become: yes

- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true
  become: yes

- name: Secures the mysql root user
  mysql_user: user="root" password="{{ db_root_password }}" host="{{ item }}" login_password="{{db_root_password}}" login_user=root
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"    

