---

- name: add mysql repo
  apt_repository:
    repo: 'deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7'
    state: present


# - name: prep for mysql-server-5.6 
#   shell: export DEBIAN_FRONTEND="noninteractive"
#   with_items:
#   become: yes
#   become_user: athill

- name: Set MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{ db_root_password | quote}}' vtype='password'

- name: Confirm MySQL root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{ db_root_password | quote}}' vtype='password'

- name: install mysql
  apt: name={{ item }} update_cache=yes state=latest force=yes
  with_items: 
    # - python-dev
    - python-mysqldb  
    - mysql-server
    - libmysqlclient-dev
    - mysql-client

- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true

  # 'localhost' needs to be the last item for idempotency, see
  # http://ansible.cc/docs/modules.html#mysql-user
  # - name: update mysql root password for all root accounts
  #   mysql_user: name=root host={{ item }} password={{ db_root_password }} priv=*.*:ALL,GRANT
  #   with_items:
  #     - "{{ ansible_hostname }}"
  #     - 127.0.0.1
  #     - ::1
  #     - localhost

  # - debug: var=db_root_password

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600  


- name: create application db
  mysql_db: name="{{ db_database }}" state=present

- name: create application user
  mysql_user: name="{{ db_user }}" password="{{ db_password }}" priv={{db_database}}.*:ALL state=present