---

  - name: install packages
    apt: name={{ item }} update_cache=yes state=latest force=yes
    with_items:
      - nodejs
      - npm

  - name: install and configure n, gulp, and webpack
    command: "{{ item }}"
    with_items:
    - npm cache clean -f
    - npm install -g n 
    - npm install -g gulp-cli
    - npm install -g webpack
    - npm install -g bower
    - n lts