---

- name: install packages
  apt: name={{ item }} update_cache=yes state=latest force=yes
  with_items:
    - make
    - g++
    - libssl-dev
    - build-essential
    - libpng-dev
  become: yes

- name: Extract node into /usr/src
  unarchive:
    src: "http://nodejs.org/dist/{{ node_version }}/node-{{ node_version }}.tar.gz"
    dest: /usr/src
    remote_src: yes
  become: yes

- name: install nodejs
  command: "{{ item }}"
  with_items: 
    - sh configure
    - make
    - make install
  become: yes
  args: 
    chdir: "/usr/src/node-{{ node_version }}"
