---

### not sure these are necessary
# - file:
#     path: "/home/{{ deploy_user_name }}/.config/composer"
#     state: directory
#     mode: 0755

# - name: add auth.json file
#   template: src=github-oauth.json.j2 dest="/home/{{ deploy_user_name }}/.config/composer/auth.json" owner="{{ deploy_user_name }}"


## node
- name: "{{ host }} set NODE_ENV"
  shell: export NODE_ENV={{ app_env }}

- name: "{{ host }} remove node_modules"
  file:
    state: absent
    path: "{{ project_dir }}/node_modules"

- name: "{{ host }} npm install"
  shell: npm install
  args:
    chdir: "{{ project_dir }}"

- name: "{{ host }} npm build"
  command: "{{ item }}"
  with_items:
    - "{{ node_build_command }}"
  args:
    chdir: "{{ project_dir }}"

### .env
- name: "{{ host }} copy .env file"
  template: src={{ app_name }}.env.j2  dest={{ project_dir }}/.env force=yes


