---
- name: disable root ssh 
  lineinfile: dest=/etc/ssh/sshd_config regexp='^(.*)PermitRootLogin' line='PermitRootLogin no'
  notify:
  - restart ssh

- name: Enable UFW
  ufw: direction=incoming policy=deny state=enabled

- name: UFW limit SSH
  ufw: rule=limit port=ssh

- name: UFW open HTTP
  ufw: rule=allow port=http

- name: UFW open HTTPS
  ufw: rule=allow port=https

- name: check if swap exists
  stat: path=/swapfile
  register: swapfile

- name: allocate swap
  command: fallocate -l 1G /swapfile creates=/swapfile

- name: mkswap
  command: mkswap /swapfile
  when: swapfile.stat.exists == False

- name: fix swapfile perms
  file: path=/swapfile owner=root group=root mode=0600 
  when: swapfile.stat.exists == False

- name: swapon
  command: swapon /swapfile
  when: swapfile.stat.exists == False

- name: write swap entry in fstab
  mount: name=none src=/swapfile fstype=swap opts=sw passno=0 dump=0 state=present
  when: swapfile.stat.exists == False

- name: install packages
  apt: name={{ item }} update_cache=yes state=latest force=yes
  with_items:
  - git
  - ntp