---

- debug: msg={{ inventory_hostname }}

- name: disable root ssh 
  lineinfile: dest=/etc/ssh/sshd_config regexp='^(.*)PermitRootLogin' line='PermitRootLogin no'
  notify:
  - restart ssh
  become: true

- name: install packages
  apt: name={{ item }} update_cache=yes state=latest force=yes
  with_items:
  - git
  - ntp
  become: true

- include_tasks: ufw.yml
  when:  inventory_hostname != 'target'

- include_tasks: swap.yml
  when:  inventory_hostname != 'target'

