---

- name: check if swap exists
  stat: path=/swapfile
  register: swapfile
  become: true

- name: allocate swap
  command: fallocate -l 2G /swapfile creates=/swapfile
  become: true

- name: mkswap
  command: mkswap /swapfile
  when: swapfile.stat.exists == False
  become: true

- name: fix swapfile perms
  file: path=/swapfile owner=root group=root mode=0600 
  when: swapfile.stat.exists == False
  become: true

- name: swapon
  command: swapon /swapfile
  when: swapfile.stat.exists == False
  become: true

- name: write swap entry in fstab
  mount: name=none src=/swapfile fstype=swap opts=sw passno=0 dump=0 state=present
  when: swapfile.stat.exists == False
  become: true