---
# php, nginx, composer
# PHP
- name: install nginx and php packages
  apt: name={{ item }} update_cache=yes state=latest force=yes
  with_items:
    - mcrypt
    - nginx
    - php{{php_version}}-cli
    - php{{php_version}}-curl
    - php{{php_version}}-fpm
    - php{{php_version}}-intl
    - php{{php_version}}-json
    - php{{php_version}}-mcrypt
    - php{{php_version}}-mbstring
    - php{{php_version}}-mysql
    - php{{php_version}}-xml
    - php-xdebug

- name: Configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/default
  notify:
    - restart php-fpm
    - restart nginx      

- name: ensure php-fpm cgi.fix_pathinfo=0
  lineinfile: dest=/etc/php/{{php_version}}/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
  notify:
    - restart php-fpm
    - restart nginx

- name: enable php mcrypt module
  shell: phpenmod mcrypt
  args:
    creates: /etc/php/cli/conf.d/20-mcrypt.ini

# composer
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
