---
- name: Install depends
  apt: name={{ item }} state=present
  with_items:
    - git 
    - bc

- name: Install lets encrypt
  git: >
    dest=/opt/letsencrypt
    repo=https://github.com/letsencrypt/letsencrypt
    update=no
  register: cloned

# - name: copy ini file
#   template: src=le-renew-webroot.ini.j2 dest=/usr/local/etc/le-renew-webroot.ini

# - name: stop nginx
#   service: name=nginx state=stopped

# - name: run letsencrypt
#   shell: ./letsencrypt-auto certonly --standalone --agree-tos --config /usr/local/etc/le-renew-webroot.ini
#   args: 
#     chdir: /opt/letsencrypt
#     creates: /etc/letsencrypt/live/{{host}}/fullchain.pem

# - name: Configure nginx
#   template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/default
#   notify:
#     - restart php-fpm

# - name: start nginx
#   service: name=nginx state=started

# - name: copy renewal script
#   template: src=le-renew-webroot dest=/usr/local/sbin/le-renew-webroot mode=0700

# - name: Install renewal cron
#   cron: name="Let's Encrypt Renewal" day=1 hour=2 minute=30 
#         job="/usr/local/sbin/le-renew-webroot >> /var/log/le-renewal.log"

## check script never implemented?
# - name: install check script
#   template: src=letsencrypt-check dest=/usr/local/sbin/letsencrypt-check mode=0700